gherlint/gherlint

- bin/gherlint.js
- defaults/configFilePattern.js
- defaults/gherlintrc.js
- defaults/index.js
- lib/cli.js
- lib/cliOptions.js
- lib/linter/linter.js
- lib/logging/logger.js
- lib/parser/parser.js
- lib/path.js
- lib/rules/index.js
- package.json
> Added config generator cli option, default config and logger

- .eslintignore
- .eslintrc
- lib/cli.js
- lib/cliOptions.js
- lib/config.js
- lib/linter/linter.js
- lib/logging/lintLogger.js
- lib/logging/logger.js
- lib/parser/parser.js
- lib/rules/defaults/indentation.js
- lib/rules/indentation.js
- package.json
> Refactor and eslint added

- lib/cli.js
- lib/cliOptions.js
- lib/config.js
- lib/linter/linter.js
- lib/logging/lintLogger.js
- lib/logging/logger.js
- lib/parser/parser.js
- package.json
> Added console colors

- lib/CliOption.js
- lib/Fs.js
- lib/GherlintConfig.js
- lib/Linter.js
- lib/defaults/gherlintrc.js
- lib/rules/Rule.js
- lib/rules/indentation.js
Added:
- `--fix` cli option (to fix the lint problems)
- added fixes for `indentation` rule
Fixes #8
> Added `--fix` CLI option

- .eslintrc
- .github/workflows/ci.yml
- .gitignore
- jest.config.js
- package.json
- tests/__fixtures__/Rules/indentation/testdata.js
- tests/lib/helpers/parser.js
- tests/lib/helpers/problemGenerator.js
- tests/lib/rules/indentation.test.js
- yarn.lock
- jest unit test setup
- unit tests for indentation rule
- CI pipeline for unit tests
part of #13 and #6
> Added unit tests for indentation rule

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
docs:
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
part of #4
> Add CONTRIBUTING and CODE_OF_CONDUCT docs

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
This PR adds the template file for the bug reports, feature requests, and pull requests. 
- Fixes https://github.com/gherlint/gherlint/issues/22
The template makes it easier for contributors to raise issues and make a pull request to the repo.
- test environment:
- test case 1:
- test case 2:
- ...
> Added template for bug report, feature request, and pull request

- lib/gherlint/GherLint.js
- lib/gherlint/GherlintConfig.js
- utils/Path.js
- Fix imports
- Search the feature files from the provided path
> Search for feature files using provided path/pattern

- CONTRIBUTING.md
- README.md
- docs/adding_new_rule.md
- Added new docs for adding a new rule
- updated Readme docs
- updated CONTRIBUTING docs to include conventional commit message
> docs: add docs on adding a new rule

- lib/cli/Cli.js
- lib/gherlint/GherLint.js
- lib/linter/Linter.js
- lib/rules/indentation.js
- tests/__fixtures__/Rules/indentation/testdata.js
- tests/lib/rules/indentation.test.js
Command `./bin/gherlint.js --fix <path-to-feature>` fixes the feature file
Open tasks:
> Implement --fix

- .github/workflows/ci.yml
- .husky/commit-msg
- .husky/pre-commit
- commitlint.config.js
- package.json
- yarn.lock
Check commit messages on commit and add PR commits checks in CI
> chore: add commitlint to lint commits

- .github/dependabot.yml
Only allow security updates. Disable version updates
> ci: allow security updates only

- lib/linter/Linter.js
- lib/rules/indentation.js
- lib/rules/no_repetitive_step_keyword.js
- tests/lib/linter/Linter.test.js
Invalid gherkin file is now reported as lint problem
- Part of https://github.com/gherlint/gherlint/issues/17
> feat(rule): report invalid gherkin file as lint problem

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .npmignore
- package.json
- yarn.lock
add publish github workflow to publish releases to the npm registry
> ci: add npm publish gh workflow

- lib/config/gherlintrc.js
- lib/rules/indentation.js
- tests/lib/rules/indentation.test.js
raise indentation severity level to error
> refactor(rule): raise indentation severity level to error

- CHANGELOG.md
- package.json
Prepare release for `1.0.0-beta.1`
> chore: prepare 1.0.0-beta.1

- package.json
- Fixes https://github.com/gherlint/gherlint/issues/71
> fix: installation on node version higher than 12 gives warning

- package.json
> chore: prepare release 1.0.0-beta.2

- lib/gherlint/GherLint.js
- lib/linter/Linter.js
- lib/rules/indentation.js
- package.json
- tests/lib/linter/Linter.test.js
Loop through each problem only once and don't re-run rules immediately. Re-lint only once per file after the fixes have been applied.
- Fixes https://github.com/gherlint/gherlint/issues/77
> fix: command freezes for long time with --fix

- lib/cli/Cli.js
- lib/logging/LintLogger.js
- tests/lib/logging/LintLogger.test.js
If there are no lint errors then gherlint reports the successful message.
**0 problem:** (exitcode 0)
**some warnings:** (exitcode 0)
- Closes https://github.com/gherlint/gherlint/issues/74
> feat: report lint successful message if there are no lint errors

- bin/gherlint.js
- global/init.js
- lib/linter/Linter.js
- lib/logging/LintLogger.js
- utils/time.js
Show the execution time and lint time after linting is completed
Before:
Now:
> feat: show execution time

- CHANGELOG.md
- package.json
> chore: prepare 1.0.0-beta.3

- CHANGELOG.md
- lib/config/gherlintrc.js
- lib/rules/index.js
- lib/rules/require_step.js
- tests/__fixtures__/Rules/require_step/fixture.js
- tests/lib/rules/require_step.test.js
🎉 New Rule Added: `require_step`
Rule metadata:
```js
meta = {
ruleId: "require_step",
type: "error"
}
```
- Part of https://github.com/gherlint/gherlint/issues/17
> feat(rule): add new rule 'require_step'

- CHANGELOG.md
- lib/config/gherlintrc.js
- lib/rules/index.js
- lib/rules/require_scenario.js
- tests/__fixtures__/Rules/require_scenario/fixture.js
- tests/lib/rules/require_scenario.test.js
🎉 New Rule Added: `require_scenario`
Rule metadata:
```js
meta = {
ruleId: "require_scenario",
type: "error"
}
```
- Part of https://github.com/gherlint/gherlint/issues/17
> feat(rule): add new rule 'require_scenario'

- lib/linter/Linter.js
Do run rules that are set to `off`
- Fixes #95
> fix: rules that has off type also get reported

- CHANGELOG.md
- Part of https://github.com/gherlint/gherlint/issues/93
> chore: document new --config cli option in changelog

- CHANGELOG.md
- package.json
Bump version to 1.0.0-rc.1
- Part of https://github.com/gherlint/gherlint/issues/93
> chore: bump version to 1.0.0-rc.1

- CHANGELOG.md
- package.json
Bump version to 1.0.0
- Part of https://github.com/gherlint/gherlint/issues/93
> chore: bump to version 1.0.0

- .github/release_template.md
- CHANGELOG.md
- package.json
> chore: prepare release 1.1.0

- .github/release_template.md
- CHANGELOG.md
- package.json
- Fixes <issue_link>
- Part of <issue_link>
- test environment:
- test case 1:
- test case 2:
> chore: bump version

- lib/index.js
- yarn.lock
This PR includes the addition of index.js to the lib folder, as it is currently missing.
- Fixes : https://github.com/gherlint/gherlint/issues/125
> fix: module resolution issues
